config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'categories#index'

  resources :categories do
    resources :recipes do
      resources :ingredients
      resources :ratings
    end
  end

  get '/profile' => 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes, through: :ingredients_recipes
  has_many :ingredients_recipes
end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :user_id, :uniqueness => { :scope => :recipe_id }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  has_many :ingredients, through: :ingredients_recipes
  has_many :ingredients_recipes
  has_many :ratings
  belongs_to :user, optional: true


  accepts_nested_attributes_for :ingredients

  validates :name, :difficulty, :prep_time, :directions, :creator, presence: true

  def average_rating
    if self.ratings.count > 0
      sum = self.ratings.reduce(0) { |rating_total, rating| rating_total + rating.rate }
      sum / self.ratings.count
    else
      "Not yet rated. :("
    end
  end

  def self.search(search) where("name ILIKE ? OR directions ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :recipes
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def categories_list
     @categories = Category.all
  end 

  helper_method :categories_list

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @appetizers = Category.find_by_name('Appetizer').recipes#.sort_by(rate)
    @salads = Category.find_by_name('Salad').recipes
    @mains = Category.find_by_name('Main Course').recipes
    @desserts = Category.find_by_name('Dessert').recipes
  end

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def new
    @category = Category.find params[:category_id]
    @recipe = Recipe.find params[:recipe_id]
    @ingredient = Ingredient.new
  end

  def edit
  end

  def create
    @category = Category.find params[:category_id]
    @recipe = Recipe.find params[:recipe_id]
    @recipe.ingredients << Ingredient.create(ingredient_params)

    redirect_to category_recipe_path(@category, @recipe)
  end

  def update
  end

  def show
  end

private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def new
  	@category = Category.find params[:category_id]
    @recipe = Recipe.find params[:recipe_id]
    @rating = Rating.new
  end

  def create
  	@category = Category.find params[:category_id]
  	@recipe = Recipe.find params[:recipe_id]
  	@rating = @recipe.ratings.new(rating_params)
  	@rating.user = current_user
  	if @rating.save
      update_average
      redirect_to category_recipe_url(@category, @recipe)
  	# if user wants to update rating
  	elsif Rating.where(recipe: @recipe, user: current_user)
  		if Rating.where(recipe: @recipe, user: current_user).update(rating_params)
        update_average
  			redirect_to category_recipe_url(@category, @recipe)
  		end
  	else
  		redirect_to new_category_recipe_rating_path(@category, @recipe)
  	end
  end

  def edit
  end

  def update
  end

private
  def rating_params
  	params.require(:rating).permit(:rate, :user, :recipe)
  end

  def update_average
    new_average = @rating.recipe.average_rating
    @rating.recipe.update_attributes(average: new_average)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @category = Category.find params[:category_id]
    @recipes = Recipe.all
    if params[:search] 
      @recipes = Recipe.search(params[:search]).order("created_at DESC")
    else 
      @recipes = Recipe.all.order("created_at DESC") 
    end
  end 

  def new
    @category = Category.find params[:category_id]
    @recipe = Recipe.new(:category => @category)
  end

  def show
    @category = Category.find(params[:category_id])
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.ingredients
    @ingredient = Ingredient.new
    @rating = Rating.new
    @ratings = @recipe.ratings
    # @recipe.average = @recipe.average_rating
  end

  def edit
    @category = Category.find(params[:category_id])
    @recipe = Recipe.find(params[:id])
  end

  def create
    @category = Category.find params[:category_id]
    @recipe = Recipe.new(recipe_params)
    @recipe[:user_id] = current_user.id
    @recipe.category = @category

    if @recipe.save
      redirect_to category_recipe_path(@category, @recipe)
    else
      flash.now[:error] = "Could not save recipe"
      render :new
    end
  end

  def update
    @category = Category.find(params[:category_id])
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to category_recipe_path(@category, @recipe), notice: 'Recipe successfully updated' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @recipe = Recipe.find (params[:id])
    @recipe.destroy
    redirect_to category_path(@category)
  end

private
  def recipe_params
    params.require(:recipe).permit(:name, :difficulty, :prep_time, :directions, :creator)
  end

  # def rating_average
  #   sum = 0
  #   @ratings.each do |rating|
  #     sum += rating.rate
  #   end
  #   sum / @ratings.length
  # end

  def rating_average
    5
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def show
    @user = current_user
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%= image_tag    'cover.jpg', media: 'all' %>

<h1 class="ui center aligned header">Menu for Mikey's Fancy Restaurant:</h1>

<div class="ui container center aligned">
  <div class="ui big celled list">
    <% @categories.each do |category| %>
    <p>
      <h2>
        <%= category.name %>s:
      </h2>
      <% category.recipes.order(average: :desc).first(5).each do |recipe| %>
        <div class="item">
          <div class="header"><%= link_to "#{recipe.name}", category_recipe_path(category, recipe) %></div>
          <div class="sub header">Recipe by: <%= recipe.creator %></div>
        </div>
        <p>
          <%= truncate(recipe.directions, length: 60) %>
        </p>
        <p>
          <%= pluralize(recipe.ingredients.length, 'ingredient') %>
        </p>
      <% end %>

    </p>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="ui center aligned header"><%= @category.name.pluralize %></h1>

<button class="ui fluid button"><%= link_to "Create a new #{@category.name.downcase}", new_category_recipe_path(@category) %></button>
<br>

<div class="ui container center aligned">
  <div class="ui big celled list">
  <% @recipes.each do |recipe| %>
    <div class="item">
      <div class="header"><%= link_to "#{recipe.name}", category_recipe_path(@category, recipe) %></div>
      <div class="sub header">Recipe by: <%= recipe.creator %></div>
    </div>
    <p>
      <%= truncate(recipe.directions, length: 60) %>
    </p>
    <p>
      <%= pluralize(recipe.ingredients.length, 'ingredient') %>
    </p>
  <% end %>
  </div>
</div>

app/views/ingredients/new.html.erb
<h1 class="ui center aligned header">Submit New Ingredient</h1>

<%= form_for [@category, @recipe, @ingredient], url: {action: "create"} do |f| %>
  Ingredient: <br>
  Name/Amount: <%= f.text_field :name %> <br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mikeys Fancy Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'semantic.min', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

   <nav class="ui menu">

    <div>
     <%= link_to "Mikey's Fancy Restaurant", '/', class: "item red" %>
    </div>
<!--     <div class="ui search item">
      <div class="ui transparent fluid icon input">
        <input class="prompt" type="text" name="Search" placeholder="Search recipes by keyword...">
        <i class="search icon"></i>
      </div>
    </div> -->
      <% categories_list.each do |category| %>
        <%= link_to "#{category.name}", category_path(category), class: "item" %>
      <% end %>
       <div class="right menu">

         <div class="ui right category search">
           <div class="ui icon input">
             <%= form_tag(category_recipes_path(category_id: 1), :method => "get", id: "search-form") do %> <%= text_field_tag :search, params[:search], placeholder: "Search Recipes" %> <%= submit_tag "Search", :name => nil %> <% end %>
             <!-- <i class="search icon"></i> -->
           </div>
           <div class="results"></div>
         </div>
         <% if current_user %>
          <%= link_to "#{current_user.name}", '/profile', class: "item" %>
          <%= link_to "Logout", '/logout',  class: "item" %>
          <% else %>

          <%= link_to 'Login', '/login', class: "item" %>
          <%= link_to 'Signup', '/signup', class: "item" %>
        </div>
      <% end %>
    </nav>
    <div class="ui container">
      <div class="ui grid">
        <div class="three column row">
          <div class="three wide column"></div>
          <div class="ten wide column">
            <%= yield %>
          </div>
          <div class="three wide column"></div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/ratings/new.html.erb
<h2>Submit New Rating</h2>

<%= form_for [@category, @recipe, @rating], url: {action: "create"} do |f| %>
  Rating <%= f.select :rate, options_for_select( [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5]] ) %> <br>
  <%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h2>Edit Existing Recipe</h2>

<%= form_for [@category, @recipe], url: {action: "update"} do |f| %>

  Recipes:
  <%= f.text_field :name %>
  <%= f.select :difficulty, options_for_select( [["Easy", "easy"], ["Medium", "medium"], ["Hard", "hard"]]) %>
  <%= f.number_field :prep_time %>
  <%= f.text_area :directions %>
  <%= f.text_field :creator %>
    <%= f.submit %>
<% end %>

<% if @recipe.errors.any? %>
  <%= @recipe.errors.messages %>
<% end %>

app/views/recipes/index.html.erb
<div class="ui container center aligned">
  <div class="ui big celled list">
  <% @recipes.each do |recipe| %>
    <div class="item">
      <div class="header"><%= link_to "#{recipe.name}", category_recipe_path(@category, recipe) %></div>
      <div class="sub header">Recipe by: <%= recipe.creator %></div>
    </div>
    <p>
      <%= truncate(recipe.directions, length: 60) %>
    </p>
    <p>
      <%= pluralize(recipe.ingredients.length, 'ingredient') %>
    </p>
  <% end %>
  </div>
</div>

<% if @recipes.blank? %>
  <h4>There are no recipes containing the term <%= params[:search] %>.</h4>
<% end %>

app/views/recipes/new.html.erb
<h1 class="ui center aligned header">Create <%= @category.name %></h1>

<%= form_for [@category, @recipe], url: {action: "create"} do |f| %>
	Recipes: <br>
	Name: <%= f.text_field :name %> <br>
	Difficulty <%= f.select :difficulty, options_for_select( [["Easy", "easy"], ["Medium", "medium"], ["Hard", "hard"]] ) %> <br>
	Prep Time (minutes) <%= f.number_field :prep_time %> <br>
	Directions <%= f.text_area :directions %> <br>
	Creator <%= f.text_field :creator %> <br>
	<%= f.submit %>
<% end %>

<% if @recipe.errors.any? %>
<%= @recipe.errors.messages %>
<% end %>

app/views/recipes/show.html.erb
<div class="ui one column grid">
  <div class="column">
    <div class="ui raised segment">
      <h1 class="ui left aligned header"><%= @recipe.name %></h1>
      <a class="ui yellow ribbon label">Rating:</a>
      <span><%= @recipe.average_rating %> <a href="<%= category_recipe_path(@recipe.category, @recipe) %>/ratings/new">[Add New rating]</a> </span>
      <p></p>
      <a class="ui red ribbon label">Difficulty:</a>
      <span><%= @recipe.difficulty %></span>
      <p></p>
      <a class="ui blue ribbon label">Prep Time:</a>
      <span><%= @recipe.prep_time %> minutes</span>
      <p></p>
      <a class="ui green ribbon label">Ingredients:</a>
      <ul>
        <% for ingredient in @ingredients %>
        <li><%= ingredient.name %></li>
        <% end %>
      </ul>
      <span></span>
      <p></p>
      <a class="ui purple ribbon label">Directions:</a>
      <span></span>
      <p><%= @recipe.directions %> </p>
      <a class="ui grey ribbon label">Creator:</a>
      <span><%= @recipe.creator %></span>
      <p> </p>
      <div class="ui one column grid">
        <div class="column">

          <%= link_to "Add new Ingredient", new_category_recipe_ingredient_path(@category, @recipe, @ingredient), class: "ui left floated teal button" %>
          <div class="ui right floated buttons">
            <%= link_to "Edit", edit_category_recipe_path(@category, @recipe), class: "ui right aligned button" %>
            <div class="or"></div>
            <%= link_to "Delete", category_recipe_path(@category, @recipe), {method: :delete, data: {confirm: 'Are you sure?'}, class: "ui right alinged red button"} %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


<!-- <div class="ui center aligned list">
  <span class="item"> <span></span> <%= @recipe.difficulty %></span>
  <div class="item"><%= @recipe.prep_time %> minutes</div>
  <div class="item"><%= @recipe.directions %></div>
  <div class="item"><%= @recipe.creator %></div>
</div> -->

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h4 class="ui horizontal divider header">Profile</h4>

<table class="ui definition table">
  <tbody>
    <tr>
      <td class="two wide column">Name</td>
      <td><%= current_user.name %></td>
    </tr>
    <tr>
      <td>Email</td>
      <td><%= current_user.email %></td>
    </tr>
  </tbody>
</table>

<h2 class="ui center aligned header"><%= current_user.name %>'s Recipes</h2>

<ul>
  <% for recipe in current_user.recipes %>
  <li><%= recipe.name %></li>
  <% end %>
</ul>